### ISSUE TITLE
Error with whisper large model

### ISSUE THREAD

**Issue by raivisdejus** [echogarden-project/echogarden#34] opened 2024-01-13 20:45 UTC
Running transcription with whisper large model crashes with error

> Create ONNX inference session for model 'large'.. 2024-01-13 22:41:57.360987848 [E:onnxruntime:, inference_session.cc:1798 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/initializer.cc:43 onnxruntime::Initializer::Initializer(const onnx::TensorProto&, const onnxruntime::Path&) [ONNXRuntimeError] : 1 : FAIL : tensorprotoutils.cc:789 GetExtDataFromTensorProto External initializer: positional_embedding offset: 0 size to read: 7680000 given file_length: 2293760 are out of bounds or can not be read in full.
> 
> Error: Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/initializer.cc:43 onnxruntime::Initializer::Initializer(const onnx::TensorProto&, const onnxruntime::Path&) [ONNXRuntimeError] : 1 : FAIL : tensorprotoutils.cc:789 GetExtDataFromTensorProto External initializer: positional_embedding offset: 0 size to read: 7680000 given file_length: 2293760 are out of bounds or can not be read in full.

I am running the transcription on Ubuntu Node `v20.3.0` with this command 
`echogarden transcribe audio.wav audio.txt --language=lv --engine=whisper --whisper.model=large`

**Comment by rotemdan** [comment] 2024-01-13 21:01
I uploaded the model when I tried adding support for the large Whisper models, especially V3. 

The lack of support to the large models was also reported earlier, on an issue opened at the end of November. Seems like the issue has been deleted by the person who opened it (I only noticed it now). The issue contained some detailed and relevant information, but it seems like there's not much I can do to restore it.

Anyway, the large models can't be loaded since `onnxruntime-node` doesn't support loading models with external data (all models over 2GB).

On 27 November 2023, I opened an [issue on the `onnxrutime` tracker](https://github.com/microsoft/onnxruntime/issues/18586) for adding this capability.

I decided to upload the large-v3 Whisper model to the Hugging Face repository anyway, in order to test the download process, and in case anyone else wants to use for it (say, with a different implementation of the ONNX runtime). 

Currently, it doesn't work, as you understand. It would only become usable when the issue is fixed in `onnxruntime-node`.

**Comment by raivisdejus** [comment] 2024-01-13 21:43
Got it! Let's see how this develops and thanks for creating the great `echogarden` :)

**Comment by rotemdan** [comment] 2024-04-12 16:56
On `v1.0.0` I just released, I added support for [`whisper.cpp`](https://github.com/ggerganov/whisper.cpp), which supports large models (`large-v1`, `large-v2`, `large-v3`), quantized models, and GPU acceleration (CUDA and OpenCL). 

All `whisper.cpp` models (including quantized models) are auto-downloaded. A CUDA build will be auto-downloaded on Windows when you set `--enableGPU`, but not on Linux. macOS requires a to set a custom executable path for `whisper.cpp`, since I don't have a mac and the binary signature requirements are problematic.

I also added support for the [OpenAI cloud platform](https://openai.com/pricing) (recognition and synthesis), which provides `large-v2` on the cloud, but it's a paid service ($0.006 / minute), and the local `whisper.cpp` GPU build can be faster if you have a modern NVIDIA GPU.

Just note the timestamps returned by `whisper.cpp` are not as accurate as the ones given by the integrated Whisper implementation (which are now getting close to the accuracy of the official OpenAI reference Python implementation). Also I've spent a lot of effort in the past week trying to improve it further, and to reduce hallucinations and repetition loops.

**Comment by rotemdan** [comment] 2024-12-05 13:07
Large models can't fully be supported until `onnxruntime-node` receives support for models over 2GB, with external data. `whisper.cpp` engine supports them (all of its models, including quantized ones, are supports).

Recently, there was also added support for a 16-bit quantized version of `large-v3-turbo` for the integrated ONNX-based Whisper engine, but my experiments show the quantization causes some non-ideal behavior when decoding (especially early ending of audio parts - it happens infrequently though).

I'm closing this issue.

**Closed by rotemdan** 2024-12-05 13:07 UTC
Labels: bug, external
