### ISSUE TITLE
Flite WASM Issues

### ISSUE THREAD

**Issue by halalsandwich** [echogarden-project/echogarden#31] opened 2023-11-24 20:12 UTC
As of v20.0.0 "The version option is now required and has no default value." [ref](https://nodejs.org/api/wasi.html#new-wasioptions)
Problematic for people using v20>

Stacktrace
node:wasi:51
    validateString(options.version, 'options.version');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.version" property must be of type string. Received undefined
    at new WASI (node:wasi:51:5)
    at Module.synthesize (nulled/node_modules/.pnpm/echogarden@0.11.16/node_modules/echogarden/dist/synthesis/FliteTTS.js:39:18)
    at async synthesizeSegment (nulled/node_modules/.pnpm/echogarden@0.11.16/node_modules/echogarden/dist/API/Synthesis.js:296:42)
    at async synthesizeSegments (nulled/node_modules/.pnpm/echogarden@0.11.16/node_modules/echogarden/dist/API/Synthesis.js:112:88) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v21.2.0

[Problematic line](https://github.com/echogarden-project/echogarden/blob/4e89cd0b834fb297fa3c02c4e13018aa837199e0/src/synthesis/FliteTTS.ts#L59)

**Comment by rotemdan** [comment] 2023-11-24 20:52
Thanks a lot for the report!

Based on Node's documentation, the `version` field was [added to the WASI API in Node `19.8.0`](https://nodejs.org/api/wasi.html#new-wasioptions).

The issue is now fixed on version `0.11.17`.

**Closed by rotemdan** 2023-11-24 20:52 UTC
